export const routeApiPaths = {
  home: () => "/api/vue/home",
  growth: () => "/api/vue/growth",
  admin: () => "/api/vue/admin",
  spb: (route = {}) => `/api/vue/spb?collection=${encodeURIComponent(route.params?.collection || "individual")}`,
  spbSync: () => "/api/vue/spb/sync",
  spbSyncStatus: (jobId) => `/api/vue/spb/sync/${encodeURIComponent(jobId)}`,
  spbBackfillDetails: () => "/api/vue/spb/backfill-details",
  lists: () => "/api/vue/lists",
  listSearch: (query) => `/api/vue/lists/search?q=${encodeURIComponent(query)}`,
  listDetail: (route) => `/api/vue/lists/${route.params.id}`,
  wrongWords: () => "/api/vue/wrong-words",
  challengeDay: (route) => `/api/vue/challenge-calendar/${route.params.day}`,
  wordDetail: (route) => `/api/vue/words/${route.params.id}${window.location.search}`,
  preview: (route) => `/api/vue/upload/preview/${route.params.id}${window.location.search}`,
  newspaper: () => "/api/vue/newspaper",
  newspaperArticle: (route) => `/api/vue/newspaper/${route.params.section}/${route.params.index}`,
};
